name: flutter_analyze

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  lint:
    name: flutter_analyze
    runs-on: ubuntu-latest
    steps:
      - name: set up repository
        uses: actions/checkout@v2
      - name: setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: false
      - name: flutter doctor
        run: flutter doctor -v
      - name: flutter pub get
        run: flutter pub get
      - name: flutter analyze
        run: flutter analyze > flutter_analyze_report.txt
